### ISSUE TITLE
[Set] 리드미 수정 및 super 파일 추가

### ISSUE THREAD

**Issue by EunHee-Jeong** [TeamRecorDream/RecorDream-iOS-AppJam#5]
### 👻 이슈 요약
- 추가적인 세팅을 진행합니다.

### ✅ 체크 리스트

- [x] 리드미 수정
- [x] Base 파일 세팅
- [x] 테스트 파일 세팅

**Comment by dev-jungbin** [comment]
정은희 파이팅 !

**Comment by EunHee-Jeong** [comment]
> 정은희 파이팅 !

뿌애애애앵ㅠ
